// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiuwrbuhzkgeynjipnof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pdXdyYnVoemtnZXluamlwbm9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2ODQ1MzgsImV4cCI6MjA4NTI2MDUzOH0.3NNfZW7pdFu-cf9_fhNENeXmggB2oahgIfI2O4JKM20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});